# GitHub Pages 配置文件
# 用于 Mining Depot USA, Inc. 官方网站

# 站点设置
title: "Mining Depot USA, Inc."
description: "专业的加密货币挖矿解决方案提供商"
url: "https://windofying.github.io"
baseurl: "/mining.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - .gitignore
  - .github/
  - Gemfile
  - Gemfile.lock

# 包含文件
include:
  - _redirects

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Mining Depot USA, Inc."

# 社交链接
social:
  name: Mining Depot USA, Inc.
  links:
    - https://www.mining-depot.com

# SEO设置
seo:
  type: "Organization"
  name: "Mining Depot USA, Inc."
  description: "专业的加密货币挖矿解决方案提供商"
  url: "https://windofying.github.io/mining.github.io"
  logo: "/images/all/mining-depot-logo.png"
